tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "yoheimuta/protolint"
brew "azure-cli"
brew "bat"
brew "cfssl"
brew "openldap"
brew "curl"
brew "direnv"
brew "dive"
brew "fzf"
brew "gh"
brew "unbound"
brew "gnutls"
brew "nghttp2"
brew "gnupg"
brew "go"
brew "helm"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "k9s"
brew "kubectx"
brew "lftp"
brew "mas"
brew "mongosh"
brew "pandoc"
brew "protobuf"
brew "qt"
brew "watch"
brew "watchman"
brew "yoheimuta/protolint/protolint"
cask "discord"
cask "font-fira-code"
cask "insomnia"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "spectacle"
cask "transmission"
cask "vlc"
cask "webpquicklook"
mas "Amphetamine", id: 937984704
mas "Color Picker", id: 1545870783
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "HEIC Converter", id: 1294126402
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SimpleMind", id: 439654198
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Teleprompter", id: 1533078079
mas "Termius", id: 1176074088
mas "Todoist", id: 585829637
mas "Xcode", id: 497799835
