tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "yoheimuta/protolint"
brew "azure-cli"
brew "exa"
brew "bat"
brew "cfssl"
brew "openldap"
brew "curl"
brew "direnv"
brew "dive"
brew "fzf"
brew "gh"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "go"
brew "helm"
brew "hey"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "k9s"
brew "kubectx"
brew "lftp"
brew "mas"
brew "mongosh"
brew "nghttp2"
brew "nmap"
brew "nvm"
brew "pandoc"
brew "protobuf"
brew "qt"
brew "shellcheck"
brew "telnet"
brew "tree"
brew "watch"
brew "watchman"
brew "yoheimuta/protolint/protolint"
cask "discord"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "insomnia"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "transmission"
cask "vlc"
cask "webpquicklook"
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "Color Picker", id: 1545870783
mas "Gifski", id: 1351639930
mas "HEIC Converter", id: 1294126402
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Teleprompter", id: 1533078079
mas "Todoist", id: 585829637
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
