return {}
-- return {
--   "nvim-telescope/telescope.nvim",
--   opts = {
--     defaults = {
--       path_display = { shorten = {
--         len = 5,
--         exclude = { 2, -1 },
--       } },
--     },
--   },
--   keys = {
--     { "<leader>fF", LazyVim.pick("files"), { root = true }, desc = "Find files (from root)" },
--     { "<leader>ff", LazyVim.pick("files"), { root = true }, desc = "Find files (cwd)" },
--     { "<leader><space>", LazyVim.pick("files"), { root = true }, desc = "Find files (cwd)" },
--   },
-- }
