-- Generated by nwg-displays on 2025-07-12 at 00:33:16. Do not edit manually.

hl.monitor({
    output = "desc:Samsung Electric Company Odyssey G80SD H1AK500000",
    mode = "3840x2160@120",
    position = "3680x735",
    scale = 1.2000000000000002
})
hl.monitor({
    output = "desc:LG Electronics LG ULTRAGEAR 202MAFCHBB91",
    mode = "highres@highrr",
    position = "2240x572",
    scale = 1.0,
    transform = 3
})
